name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  KOKA_VERSION: 3.2.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache Koka setup
        id: cache-koka
        uses: actions/cache@v4
        with:
          key: koka-setup-${{ env.KOKA_VERSION }}
          path: |
            ./koka-compiler

      - name: Setup Koka
        if: steps.cache-koka.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://github.com/koka-lang/koka/releases/download/v${{ env.KOKA_VERSION }}/install.sh > install-koka.sh
          sudo sh install-koka.sh -- --prefix=$PWD/koka-compiler       
      
      - name: Setup Koka path
        run: |
          echo "$PWD/koka-compiler/bin" >> $GITHUB_PATH

      # I don't want to create package.json or yarn.lock to support actions/setup-node
      - name: Cache JS minifier
        id: cache-js-minify
        uses: actions/cache@v4
        with:
          key: js-minifier
          path: |
            ./node_modules

      - name: Setup JS minifier
        if: steps.cache-js-minify.outputs.cache-hit != 'true'
        run: |
          npm install --save-dev rollup @rollup/plugin-terser

      - name: Build
        run: |
          ./install_libs.sh
          mkdir -p build

          koka -c src/extractor/extract.kk -i./src -i./libs --target=c -O3 \
            --cclibdir=$(dirname $(g++ --print-file-name=libstdc++.a)) --cclibdir=$(dirname $(g++ --print-file-name=libicuuc.a)) \
            --ccopts="-ffunction-sections -fdata-sections -fomit-frame-pointer" --cclinkopts="-Wl,--gc-sections,-s" \
            -obuild/indexer
          chmod +x build/indexer

          koka -c src/frontend/search.kk -i./src -i./libs --target=js -O3
          npx rollup .koka/*/js-drelease*/frontend_search__main.mjs --file build/search.min.mjs --format esm --plugin @rollup/plugin-terser

          tar -czvf build/release.tar.gz -C build indexer search.min.mjs

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/release.tar.gz

          